create table public.profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  shop_name text not null check (char_length(shop_name) between 1 and 100),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.orders (
  id bigint generated by default as identity primary key,
  seller_id uuid not null references auth.users(id) on delete cascade,
  receiver_name text not null check (char_length(receiver_name) between 2 and 10),
  phone text not null check (phone ~ '^09[0-9]{8}$'),
  store_code text not null check (store_code ~ '^[0-9]{6}$'),
  store_name text not null default '',
  store_address text not null default '',
  product text not null check (char_length(product) between 1 and 40),
  amount integer not null check (amount > 0),
  shipping_fee integer not null default 0 check (shipping_fee >= 0),
  note text not null default '' check (char_length(note) <= 60),
  created_at timestamptz not null default now()
);

create table public.customers (
  id bigint generated by default as identity primary key,
  seller_id uuid not null references auth.users(id) on delete cascade,
  name text not null check (char_length(name) between 2 and 10),
  phone text not null check (phone ~ '^09[0-9]{8}$'),
  store_code text not null check (store_code ~ '^[0-9]{6}$'),
  store_name text not null default '',
  store_address text not null default '',
  created_at timestamptz not null default now()
);

create table public.blacklist_reports (
  id bigint generated by default as identity primary key,
  seller_id uuid not null references auth.users(id) on delete cascade,
  phone text not null check (phone ~ '^09[0-9]{8}$'),
  report_count integer not null default 1 check (report_count > 0),
  note text not null default '' check (char_length(note) <= 60),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (seller_id, phone)
);

create index orders_seller_created_idx on public.orders (seller_id, created_at desc);
create index customers_seller_created_idx on public.customers (seller_id, created_at desc);
create index blacklist_reports_seller_phone_idx on public.blacklist_reports (seller_id, phone);

alter table public.profiles enable row level security;
alter table public.orders enable row level security;
alter table public.customers enable row level security;
alter table public.blacklist_reports enable row level security;

revoke all on public.profiles, public.orders, public.customers, public.blacklist_reports from anon, authenticated;
grant select, insert, update, delete on public.profiles, public.orders, public.customers, public.blacklist_reports to authenticated;
grant usage, select on all sequences in schema public to authenticated;

create policy "profiles_select_own" on public.profiles for select to authenticated
using ((select auth.uid()) = user_id);
create policy "profiles_insert_own" on public.profiles for insert to authenticated
with check ((select auth.uid()) = user_id);
create policy "profiles_update_own" on public.profiles for update to authenticated
using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);
create policy "profiles_delete_own" on public.profiles for delete to authenticated
using ((select auth.uid()) = user_id);

create policy "orders_select_own" on public.orders for select to authenticated
using ((select auth.uid()) = seller_id);
create policy "orders_insert_own" on public.orders for insert to authenticated
with check ((select auth.uid()) = seller_id);
create policy "orders_update_own" on public.orders for update to authenticated
using ((select auth.uid()) = seller_id) with check ((select auth.uid()) = seller_id);
create policy "orders_delete_own" on public.orders for delete to authenticated
using ((select auth.uid()) = seller_id);

create policy "customers_select_own" on public.customers for select to authenticated
using ((select auth.uid()) = seller_id);
create policy "customers_insert_own" on public.customers for insert to authenticated
with check ((select auth.uid()) = seller_id);
create policy "customers_update_own" on public.customers for update to authenticated
using ((select auth.uid()) = seller_id) with check ((select auth.uid()) = seller_id);
create policy "customers_delete_own" on public.customers for delete to authenticated
using ((select auth.uid()) = seller_id);

create policy "blacklist_select_own" on public.blacklist_reports for select to authenticated
using ((select auth.uid()) = seller_id);
create policy "blacklist_insert_own" on public.blacklist_reports for insert to authenticated
with check ((select auth.uid()) = seller_id);
create policy "blacklist_update_own" on public.blacklist_reports for update to authenticated
using ((select auth.uid()) = seller_id) with check ((select auth.uid()) = seller_id);
create policy "blacklist_delete_own" on public.blacklist_reports for delete to authenticated
using ((select auth.uid()) = seller_id);
